data:
  name: 'VA'
  datapath: '/data/yangchangfan/DiffusionPDE/data/testing/VA'
  offset: 
    - 10001


test:
  pre-trained: "/home/yangchangfan/CODE/DiffusionPDE/pretrained-VA/001/network-snapshot-007560.pkl"
  iterations: 1000
generate:
  seed: 0
  device: 'cuda'
  batch_size: 1
  sigma_min: 0.002
  sigma_max: 80
  rho: 7
  zeta_obs_a: 200
  zeta_obs_u: 200
  zeta_pde: 1